version: "3.9"

services:
  postgresql:
    image: postgres:14.2
    container_name: postgresql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=crawler
      - POSTGRES_PASSWORD=crawler
      - POSTGRES_DB=github_crawler
      - POSTGRES_HOST=5432
    command: -p 5432
    volumes:
     - db:/var/lib/postgresql/data
volumes:
  db:
