version: '3.9'

services:
  repo-spider-scrapy-only:
    image: crawler-github-repo-scrapy:v1.0.0
    command: scrapy crawl repos -a limit=100
    depends_on:
      - redis
      - postgres
    networks:
      - monitoring
  repo-spider:
    image: crawler-github-repo:v1.0.0
    command: scrapy crawl repos -a limit=100
    depends_on:
      - redis
      - postgres
    networks:
      - monitoring

  # ReleaseCommitSpider workers (5 replicas)
  release-commit-worker:
    image: crawler-github-commit-release:v1.0.0
    command: scrapy crawl release_commits
    depends_on:
      - redis
      - postgres
    networks:
      - monitoring
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure

  # Redis
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
#    volumes:
#      - redis_data:/data
    command: redis-server --save ""  # Vô hiệu hóa lưu trữ RDB
    networks:
      - monitoring

  # PostgreSQL
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=crawler
      - POSTGRES_PASSWORD=crawler
      - POSTGRES_DB=github_crawler
      - POSTGRES_HOST=5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - monitoring

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.51.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - redis-exporter
    networks:
      - monitoring

  # cAdvisor (để thu thập metrics CPU)
#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:v0.49.1
#    ports:
#      - "8080:8080"
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:ro
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#      - /dev/disk/:/dev/disk:ro
#    devices:
#      - /dev/kmsg
#    networks:
#      - monitoring

  # Grafana
  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
#    volumes:
#      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - monitoring

  # Redis Exporter
  redis-exporter:
    image: oliver006/redis_exporter:v1.58.0
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_EXPORTER_CHECK_KEYS=repos:requests
    depends_on:
      - redis
    networks:
      - monitoring

volumes:
  redis_data:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  monitoring:
    driver: bridge